ZamaTronicts/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ZamaTronicts.Models
{
    public class ProductViewModel
    {
        // create constructor for a single/list of product
        public ProductPO singleProductPO { get; set; }
        public List<ProductPO> listProductPO { get; set; }
        public int userTableID { get; set; }
        public int accountInfoID { get; set; }

        // create the method for the productViewModel
        public ProductViewModel()
        {
            // instaniate a new instance of the single product and list of products
            singleProductPO = new ProductPO();
            listProductPO = new List<ProductPO>();
        }
    }
}

ZamaTronicts/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using ZamaTronicts.Models;

namespace ZamaTronicts.Controllers
{
    public class ProductController : Controller
    {
        // instaniate a new instance of the mapper and DataAccess objects
        static Mapper _mapper = new Mapper();
        static ProductDataAccess _productDataAccess = new ProductDataAccess();
        static SupplierDataAccess _supplierDataAccess = new SupplierDataAccess();

        // create the get/post methods to create a product
        [HttpGet]
        public ActionResult CreateProduct()
        {
            if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
            {
                DropDown();
                // create a new instance of the viewModel
                ProductViewModel productViewModel = new ProductViewModel();

                // return the view and pass an instance of singleProduct
                return View(productViewModel.singleProductPO);
            }
            return RedirectToAction("ViewProducts");
        }

        [HttpPost]
        public ActionResult CreateProduct(ProductPO productToMap)
        {
            // call the dropdown method to view the possible suppliers
            DropDown();
           
            // pass the elements of the product to the map through the method call and then to the DAL
            _productDataAccess.AddProduct(_mapper.Map(productToMap));

            // return the user to the view product page
            return RedirectToAction("ViewProducts");
        }

        // create a post and get method to update products by passing the ID of that product
        [HttpGet]
        public ActionResult UpdateProduct(int productID)
        {
            if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
            {
                // create a new instance of the productViewModel
                ProductViewModel _productViewModel = new ProductViewModel();

                // pass the product ID to the view method and pass to the product dataAccess 
                //through the mapper then to the single product
                _productViewModel.singleProductPO = _mapper.Map(_productDataAccess.ViewOneProduct(productID));

                // return the view with productview.singleproduct
                return View(_productViewModel.singleProductPO);
            }
            return RedirectToAction("ViewProducts");
        }

        [HttpPost]
        public ActionResult UpdateProduct(ProductPO productToMap)
        {
            // pass the product through the mapper to the method and then to the DAL
            _productDataAccess.UpdateProduct(_mapper.Map(productToMap));

            // return the user to the list of products
            return RedirectToAction("ViewProducts");
        }

        // create a get to view all of the products
        [HttpGet]
        public ActionResult ViewProducts()
        {
            // create a new instance of productViewModel
            ProductViewModel _productViewModel = new ProductViewModel();
            _productViewModel.userTableID = (int)Session["userTableID"];
           
            // call the method and pass the info
            _productViewModel.listProductPO = _mapper.Map(_productDataAccess.ViewAllProducts());
           
            // return the view
            return View(_productViewModel);
        }

        // create a method to delete a book
        [HttpGet]
        public ActionResult DeleteProduct(int productID)
        {
            if ((string)Session["roleName"] == "admin")
            {
                // pass the id to the method then to the DAL
                _productDataAccess.DeleteProduct(productID);
            }

            // return the view products page
            return RedirectToAction("ViewProducts");
        }

        // create the dropdown method for the list of avaible suppliers
        [HttpGet]
        private void DropDown()
        {
            // create a new list
            ViewBag.ListSuppliers = new List<SelectListItem>();
            
            // call the method and map info to the list
            List<SupplierPO> supplier = _mapper.Map(_supplierDataAccess.ViewAllSuppliers());
            
            // create a foreach loop to loop through the avaiable suppliers
            foreach (SupplierPO suppliers in supplier)
            {
                ViewBag.ListSuppliers.Add(new SelectListItem { Text = suppliers.supplierName, Value = suppliers.supplierID.ToString() });
            }
        }
      
    }
}

ZamaTronicts/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using ZamaTronicts.Models;

namespace ZamaTronicts.Controllers
{
    public class SupplierController : Controller
    {
        // instaniate a new instance of the mapper and supplierDataAccess
        static Mapper _mapper = new Mapper();
        static SupplierDataAccess _supplierDataAccess = new SupplierDataAccess();

        // create the get/post methods to create a supplier
        [HttpGet]
        public ActionResult CreateSupplier()
        {
            if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
            {
                // create a new instance of the viewModel
                SupplierViewModel supplierViewModel = new SupplierViewModel();

                // return the view and pass an instance of singleSupplier
                return View(supplierViewModel.singleSupplierPO);
            }
            return RedirectToAction("ViewProducts");
        }

        [HttpPost]
        public ActionResult CreateSupplier(SupplierPO supplierToMap)
        {
            // pass the elements of the supplier to the map through the method call and then to the DAL
            _supplierDataAccess.AddSupplier(_mapper.Map(supplierToMap));

            // return the user to the view supplier page
            return RedirectToAction("ViewSuppliers");
        }

        // create a post and get method to update supplier by passing the ID of that supplier
        [HttpGet]
        public ActionResult UpdateSupplier(int supplierID)
        {
            if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
            {
                // create a new instance of the productViewModel
                SupplierViewModel _supplierViewModel = new SupplierViewModel();

                // pass the supplier ID to the view method and pass to the product dataAccess 
                //through the mapper then to the single supplier
                _supplierViewModel.singleSupplierPO = _mapper.Map(_supplierDataAccess.ViewOneSupplier(supplierID));

                // return the view with supplierview.singleproduct
                return View(_supplierViewModel.singleSupplierPO);
            }
            return RedirectToAction("ViewProducts");
        }

        [HttpPost]
        public ActionResult UpdateSupplier(SupplierPO supplierToMap)
        {
            // pass the supplier through the mapper to the method and then to the DAL
            _supplierDataAccess.UpdateSupplier(_mapper.Map(supplierToMap));

            // return the user to the list of suppliers
            return RedirectToAction("ViewSuppliers");
        }

        // create a get to view all of the suppliers
        [HttpGet]
        public ActionResult ViewSuppliers()
        {
            if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
            {
                // create a new instance of supplerViewModel
                SupplierViewModel _supplierViewModel = new SupplierViewModel();

                // call the view suppliers method pass it through the dataAccess and mapper
                // then set it to the supplier list
                _supplierViewModel.listSupplierPO = _mapper.Map(_supplierDataAccess.ViewAllSuppliers());

                // return the view
                return View(_supplierViewModel);
            }
            return RedirectToAction("ViewProducts");
        }

        // create a method to delete a book
        [HttpGet]
        public ActionResult DeleteSupplier(int supplierID)
        {
            if ((string)Session["roleName"] == "admin")
            {
                // pass the id to the method then to the DAL
                _supplierDataAccess.DeleteSupplier(supplierID);
            }
            // return the view suppler page
            return RedirectToAction("ViewSuppliers");
        }
    }
}

ZamaTronicts/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using DAL.Objects;
using ZamaTronicts.Models;

namespace ZamaTronicts.Controllers
{
    public class UserController : Controller
    {
        // create a new instance of the mapper and userViewModel
        static UserDataAccess _userDataAccess = new UserDataAccess();
        static Mapper _mapper = new Mapper();

        // create a post and get method to create a new user
        [HttpGet]
        public ActionResult CreateUser()
        {
            // create a new instance  of userModel
            UserPO _userModel = new UserPO();

            // set the default role value of one which is customer
            _userModel.userRole = 1;

            // return the userModel and view
            return View(_userModel);
        }

        // create a method to create a new user
        [HttpPost]
        public ActionResult CreateUser(UserPO userModel)
        {
            // pass the user model through the mapper to the method
            _userDataAccess.CreateUser(_mapper.Map(userModel));

            // return to the login page
            return RedirectToAction("Login");
        }

        // create the get/post update methods to update the user info
        [HttpGet]
        public ActionResult UpdateUser(int userTableID)
        {
            // call the dropdown method to view available roles
            DropDown();

            // instaniate a new usermodel
            UserViewModel _userModel = new UserViewModel();

            // pass the userID to the view method through the DAL
            // then pass through the mapper and set to the single user
            _userModel.singleUserPO = _mapper.Map(_userDataAccess.ViewOneUser(userTableID));

            //return the view with the single user
            return View(_userModel.singleUserPO);
        }

        [HttpPost]
        public ActionResult UpdateUser(UserPO userToMap)
        {

            // pass the user through the mapper to the method in the DAL
            _userDataAccess.UpdateUser(_mapper.Map(userToMap));

            if ((string)Session["roleName"] == "customer")
            {
                return RedirectToAction("ViewProducts", "Product");
            }
                // return to a list of users
                return RedirectToAction("ViewUsers");
        }

        // create a get method to view all of the users
        [HttpGet]
        public ActionResult ViewUsers()
        {
            //create a new instance of userViewModels
            UserViewModel _userViewModel = new UserViewModel();

            // call the method and pass through the DAL to the mapper then pass to the user list
            _userViewModel.listUserPO = _mapper.Map(_userDataAccess.ViewAllUsers());

            // return the viewModel
            return View(_userViewModel);
        }

        // create a get method to delete a user
        [HttpGet]
        public ActionResult DeleteUser(int userTableID, int accountInfoID)
        {
            if ((string)Session["roleName"] == "admin")
            {
                // pass the userID to the method in the DAL
                _userDataAccess.DeleteUser(userTableID, accountInfoID);
            }
            // return the view to view all of the users
            return RedirectToAction("ViewUsers");
        }

        // create the get/post login methods
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserPO userModel)
        {
            // check to make sure the user is accessing the right view/browser
            if (ModelState.IsValid)
            {
                // map the info
                UserDAO _user = _userDataAccess.LoginUser(_mapper.Map(userModel));

                // if the user does not exist take them to the create user page
                if (_user.userPassword == userModel.userPassword)
                {
                    // put the user values to the sesion variables
                    Session["userTableID"] = _user.userTableID;
                    Session["roleName"] = _user.roleName;
                    Session["userRole"] = _user.userRole;
                }
                else
                {
                    // display message if the info does not match

                    ViewBag.errorMessage = "Incorrect username/password";

                    // return the view
                    return View();
                }

            }
            return RedirectToAction("ViewProducts", "Product");
        }

        // create method for user logout
        [HttpGet]
        public ActionResult Logout()
        {
            // abandon the session
            Session.Abandon();

            // return home
            return RedirectToAction("Index", "Home");
        }

        // create a dropdown method to view all available roles
        [HttpGet]
        private void DropDown()
        {
            // create a new list 
            ViewBag.ListRoles = new List<SelectListItem>();
            List<UserPO> role = _mapper.Map(_userDataAccess.ViewAllRoles());

            // loop through the roles
            foreach (UserPO roles in role)
            {
                ViewBag.ListRoles.Add(new SelectListItem { Text = roles.roleName, Value = roles.userRole.ToString() });
            }
        }

        [HttpGet]
        public ActionResult CreateRole()
        {
            // create a new instance  of userModel
            UserPO _userModel = new UserPO();

            // return the userModel and view
            return View(_userModel);
        }

        [HttpPost]
        public ActionResult CreateRole(UserPO userModel)
        {
            // pass the user model through the mapper to the method  
            _userDataAccess.CreateRole(_mapper.Map(userModel));

            // return to the login page
            return RedirectToAction("Login");
        }
    }
}

ZamaTronicts/Views/Product/CreateProduct.cshtml
@model ZamaTronicts.Models.ProductPO

@{
    ViewBag.Title = "CreateProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Home", "ViewProducts", "Product", new { area = "" }, new { @class = "navbar-brand" })
        </div>
    </div>
</div>
<h2>Create A ZamaTronicts Product</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ProductPO</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.supplier, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.supplierID, (List<SelectListItem>)ViewBag.ListSuppliers, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.supplierID, "", new { @class = "text-danger" })
        </div>
    </div>












    <div class="form-group">
        @Html.LabelFor(model => model.productDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productProcessor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productProcessor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productProcessor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productOperatingSystem, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productOperatingSystem, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productOperatingSystem, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productQuantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productQuantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productRam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productRam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productRam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productPrice, "", new { @class = "text-danger" })
        </div>
    </div>




    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}



<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ZamaTronicts/Views/Product/ViewProducts.cshtml
@model ZamaTronicts.Models.ProductViewModel

@{
    ViewBag.Title = "ViewProducts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            @if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
            {
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="dropdown">
                        <ul class=" nav narbar-nav">
                            <li class=" dropdown">
                                <a href="#" data-toggle="dropdown" class=" dropdown-toggle">
                                    Product<span class=" caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class=" active"> @Html.ActionLink("Add A Product", "CreateProduct", "Product")</li>
                    </div>
                </div>
            }
            @if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
            {
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="dropdown">
                        <ul class=" nav narbar-nav">
                            <li class=" dropdown">
                                <a href="#" data-toggle="dropdown" class=" dropdown-toggle">
                                    Suppliers<span class=" caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class=" active"> @Html.ActionLink("View all of the Suppliers", "ViewSuppliers", "Supplier")</li>
                                    <li class=" active"> @Html.ActionLink("Add a Supplier", "CreateSupplier", "Supplier")</li>
                    </div>
                </div>
            }

            @if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
            {
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="dropdown">
                        <ul class=" nav narbar-nav">
                            <li class=" dropdown">
                                <a href="#" data-toggle="dropdown" class=" dropdown-toggle">
                                    Users<span class=" caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class=" active"> @Html.ActionLink("View all of the Users", "ViewUsers", "User")</li>
                                    <li class=" active"> @Html.ActionLink("Add a User", "CreateUser", "User")</li>
                                </ul>
                        </ul>
                    </div>
                </div>
            }


            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if ((string)Session["roleName"] == "customer")
                {
                    @Html.ActionLink("View Cart", "ViewCart", "Cart", new { userTableID = Model.userTableID }, new { @class = " nav narbar-nav", @style = "padding: 3px" })
                  
                }


            </div>

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if ((string)Session["roleName"] == "customer")
                {
                    @Html.ActionLink("Update", "UpdateUser", "User", new { userTableID = (int)Session["userTableID"] }, new { @class = " nav narbar-nav", @style = "padding: 3px" })
                }


            </div>


            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if ((string)Session["roleName"] == null)
                {
                    @Html.ActionLink("Login", "Login", "User", new { area = "" }, new { @class = " nav narbar-nav", @style = "padding: 3px" })
                }
                @if ((string)Session["roleName"] != null)
                {
                    @Html.ActionLink("Logout", "Logout", "User", new { area = "" }, new { @class = " nav narbar-nav", @style = "padding: 3px" })

                }

            </div>
        </div>
    </div>


    <h2> ZamaTronict Products</h2>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.singleProductPO.supplierName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.singleProductPO.productDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.singleProductPO.productProcessor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.singleProductPO.productOperatingSystem)
            </th>

            <th>
                @if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
                {
                    @Html.DisplayNameFor(model => model.singleProductPO.productQuantity)
                }
            </th>
            <th>
                @Html.DisplayNameFor(model => model.singleProductPO.productRam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.singleProductPO.productPrice)
            </th>

        </tr>

        @foreach (var item in Model.listProductPO)
        {
            <tr>

                @Html.HiddenFor(modelItem => Model.userTableID)

                @Html.HiddenFor(modelItem => item.productID)

                @Html.HiddenFor(modelItem => item.supplierID)

                <td>
                    @Html.DisplayFor(modelItem => item.supplierName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.productDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.productProcessor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.productOperatingSystem)
                </td>
                <td>
                    @if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
                    {
                        @Html.DisplayFor(modelItem => item.productQuantity)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.productRam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.productPrice)
                </td>
                <td>
                    @if ((string)Session["roleName"] == "admin" || (string)Session["roleName"] == "moderator")
                    {

                        @Html.ActionLink("Update", "UpdateProduct", new { productID = item.productID })

                    }
                </td>
                <td>
                    @if ((string)Session["roleName"] == "admin")
                    {
                        @Html.ActionLink("Delete", "DeleteProduct", new { productID = item.productID })
                    }
                </td>
                <td>
                    @if ((string)Session["roleName"] == "customer")
                    {
                        @Html.ActionLink("Add to Cart", "AddToCart", "Cart", new { productID = item.productID }, new { @class = "" })
                    }
                </td>


            </tr>
        }

    </table>
  
</body>